-- ============================================================
-- MORGUE SEIMEI — Schéma v3 (avec superviseurs)
-- ============================================================

drop table if exists morgue_corps;
drop table if exists morgue_users;

create table morgue_users (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  nom text not null unique,
  sceau text not null,
  role text default 'membre',
  banni boolean default false
);
alter table morgue_users enable row level security;
create policy "ins_user" on morgue_users for insert to anon with check (true);
create policy "sel_user" on morgue_users for select to anon using (true);
create policy "upd_user" on morgue_users for update to anon using (true) with check (true);

create table morgue_corps (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  nom text not null default 'Inconnu',
  prenom text default '',
  grade text default 'Inconnu',
  village text default 'Sunagakure',
  date_deces date,
  cause text default 'Inconnue',
  circonstances text default 'Inconnues',
  lieu_deces text default '',
  ramene_par text default '',
  admis_par text default '',
  localisation text default 'caisson',
  statut text default 'admis',
  autopsie_medecin text default '',
  autopsie_date date,
  autopsie_observations text default '',
  autopsie_prelevements text default '',
  autopsie_conclusions text default '',
  liberation_date date,
  liberation_destinataire text default '',
  liberation_type text default '',
  liberation_autorise_par text default '',
  notes text default '',
  caisson_numero int default null,
  derniere_modif_par text default '',
  derniere_modif_date timestamptz default now()
);
alter table morgue_corps enable row level security;
create policy "ins_corps" on morgue_corps for insert to anon with check (true);
create policy "sel_corps" on morgue_corps for select to anon using (true);
create policy "upd_corps" on morgue_corps for update to anon using (true) with check (true);
create policy "del_corps" on morgue_corps for delete to anon using (true);
